const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
  cooldown: 5,
  data: new SlashCommandBuilder()
    .setName('8ball')
    .setDescription('Ask the magic 8-ball a question!')
    .addStringOption(option =>
      option.setName('question')
        .setDescription('The question you want to ask')
        .setRequired(true)),
  async execute(interaction) {
    const guildColours = await require('../../database').getGuildBotColours(interaction.guild.id)
    // List of possible responses
    const responses = [
      'Yes.',
      'No.',
      'Maybe.',
      'Definitely!',
      'Absolutely not.',
      'Probably.',
      'Probably not.',
      'I don\'t think so.',
      'Meh.',
      'Sure, why not?',
      'Ask again later.',
      'I don\'t care.',
      'Go away.',
      'No u.',
      'LOL NO.',
      'When pigs can fly.',
      'What a dumb question, don\'t waste my time.',
      'It\'s possible.',
      'It\'s unlikely.',
      'Don\'t count on it.',
      'I would say yes.',
      'I would say no.',
      'There\'s a good chance.',
      'There\'s a slim chance.',
      'LOL NAH KEEP DREAMIN\' BUCKO.',
      'Yeah no.',
      'Absolutely!',
      'No way.',
      'Of course!',
      'Not in a million years.',
      'Certainly.',
      'Not a chance.',
      'Without a doubt.',
      'I doubt it.',
      'For sure!',
      'Negative.',
      'Affirmative.',
      'Nope.',
      'You bet!',
      'Don\'t think so.',
      'Sure thing!',
      'Nah.',
      'Why not?',
      'No way, Jose!',
      'Totally!',
      'In your dreams.',
      'Absolutely sure!',
      'Fat chance.',
      'Without question.',
      'No can do.',
      'Bingo!',
      'Forget it.',
      'Yes, indeed!',
      'Not on your life.',
      'Indubitably.',
      'Nuh-uh.',
      'Thumbs up!',
      'Thumbs down.',
      'Roger that!',
      'Denied.',
      'Yup!',
      'Nope.',
      'Aye aye!',
      'No sir.',
      '100% yes.',
      '0% chance.',
      'Absolutely yes.',
      'Absolutely no.',
      'In a heartbeat.',
      'Not in this lifetime.',
      'Sure!',
      'Not sure.',
      'I think so.',
      'I think not.',
      'I suppose.',
      'I don\'t suppose.',
      'It\'s a yes from me.',
      'It\'s a no from me.',
      'Why not give it a shot?',
      'Better not.',
      'Yes, please!',
      'No, thanks.',
      'I\'m in.',
      'I\'m out.',
      'Sounds good.',
      'Doesn\'t sound good.',
      'You got it!',
      'Not happening.',
      'Consider it done.',
      'Forget about it.',
      'Go for it!',
      'Hold off on that.',
      'Surely!',
      'No way, Jose!',
      'Absolutely positive!',
      'Highly doubtful.',
      'No doubt about it.',
      'Out of the question.',
      'Yep!',
      'No chance.',
      'I reckon so.',
      'I reckon not.',
      'Certainly yes.',
      'Certainly no.',
      'I guess so.',
      'I guess not.',
      'Positively!',
      'Negatively.',
      'By all means!',
      'Over my dead body.',
      'Yes, totally!',
      'No, definitely not.',
      'All signs point to yes.',
      'Outlook not so good.',
      'As I see it, yes.',
      'My sources say no.',
      'Yes, in due time.',
      'Don\'t bet on it.',
      'Count me in.',
      'Count me out.',
      'Yes, just do it!',
      'No, stop right there.',
      'I would bet on it.',
      'I wouldn\'t bet on it.',
      'You have my blessing.',
      'No blessing from me.',
      'Yes, absolutely!',
      'No way, not ever.',
      'That\'s a yes.',
      'That\'s a no.',
      'For sure!',
      'Not even close.',
      'Yes, indeed!',
      'Not in the slightest.',
      'You got it!',
      'Nope, nada.',
      'Yes, siree!',
      'Nope, never.',
      'Most certainly.',
      'Most unlikely.',
      'You\'re on!',
      'You\'re off.',
      'Consider it a yes.',
      'Consider it a no.',
      'Yep, you betcha!',
      'Nope, not a chance.',
      'Yes, let\'s do it!',
      'No, let\'s not.',
      'Affirmative, captain!',
      'Negative, ghostrider.',
      'Yes, with bells on.',
      'No, not in a million years.',
      'I\'m all for it.',
      'I\'m against it.',
      'Yes, positively.',
      'No, definitely not.',
      'It\'s a green light.',
      'It\'s a red light.',
      'Go ahead!',
      'Hold your horses.',
      'Yes, and how!',
      'No, not ever.',
      'Yes, without question.',
      'No, and that\'s final.',
      'It\'s a sure thing.',
      'It\'s a long shot.',
      'You have my approval.',
      'Not approved.',
      'Yes, without hesitation.',
      'No, with great hesitation.',
      'Yes, that\'s right.',
      'No, that\'s wrong.',
      'Yes, go for it!',
      'No, halt!',
      'Yes, and I mean it!',
      'No, and I mean it!',
      'With all my heart, yes.',
      'Not on your life, no.',
      'Yes, certainly!',
      'No, certainly not.',
      'Yes, why not?',
      'No, why bother?',
      'Yes, 100%.',
      'No, 0%.',
      'Yes, without a doubt!',
      'No, don\'t even think about it.',
      'Yes, always.',
      'No, never.',
      'Yes, you should.',
      'No, you shouldn\'t.',
      'Yes, indeed!',
      'No, indeed not.',
      'Yes, you can count on it.',
      'No, don\'t count on it.',
      'Yes, go right ahead.',
      'No, stop right now.',
      'Yes, it\'s true.',
      'No, it\'s false.',
      'Yes, for sure.',
      'No, for sure not.',
      'Yes, go for it!',
      'No, hold back.',
      'Yes, definitely!',
      'No, definitely not!',
      'Yes, trust me.',
      'No, trust me not.',
      'Yes, go ahead.',
      'No, don\'t do it.',
      'Yes, indeed!',
      'No, indeed not.',
      'Yes, and then some!',
      'No, not even a little.',
      'Yes, why not?',
      'No, not a good idea.',
      'Yes, go for it!',
      'No, better not.',
      'Yes, it\'s worth it.',
      'No, it\'s not worth it.',
      'Yes, trust me.',
      'No, don\'t trust me.',
      'Yes, absolutely!',
      'No, absolutely not.',
      'Yes, go right ahead.',
      'No, don\'t even think about it.',
      'Yes, and that\'s final.',
      'No, and that\'s final.',
      'Yes, it\'s a good idea.',
      'No, it\'s a bad idea.',
      'Yes, of course.',
      'No, of course not.',
      'Yes, you should.',
      'No, you shouldn\'t.',
      'Yes, it\'s possible.',
      'No, it\'s impossible.',
      'Yes, by all means.',
      'No, by no means.',
      'Yes, give it a try.',
      'No, don\'t try it.',
      'Yes, indeed.',
      'No, indeed not.',
      'Yes, for sure.',
      'No, for sure not.',
      'Yes, why not?',
      'No, why bother?',
      'Yes, it\'s worth it.',
      'No, it\'s not worth it.',
      'Yes, I recommend it.',
      'No, I don\'t recommend it.',
      'Yes, go ahead.',
      'No, don\'t do it.',
      'Yes, certainly!',
      'No, certainly not!',
      'Yes, that\'s correct.',
      'No, that\'s incorrect.',
      'Yes, it\'s okay.',
      'No, it\'s not okay.',
      'Yes, go for it.',
      'No, hold back.',
      'Yes, it\'s worth a shot.',
      'No, it\'s not worth it.',
      'Yes, absolutely.',
      'No, absolutely not.',
      'Yes, go right ahead.',
      'No, stop right there.',
      'Yes, it\'s a good idea.',
      'No, it\'s a bad idea.',
      'Yes, you should do it.',
      'No, you shouldn\'t do it.',
      'Yes, give it a shot.',
      'No, don\'t even think about it.',
      'Yes, without a doubt.',
      'No, not in a million years.',
      'Yes, it\'s a go.',
      'No, it\'s a no-go.',
      'Yes, do it!',
      'No, don\'t do it!',
      'Yes, go for it.',
      'No, hold back.',
      'Yes, give it a try.',
      'No, it\'s not worth it.',
      'Yes, I recommend it.'
    ];

    // Generate a random index to pick a response
    const randomIndex = Math.floor(Math.random() * responses.length);

    // Reply with the random response
    const embed = new EmbedBuilder()
      .setTitle('🎱 8-Ball')
      .setDescription(`Question: ${interaction.options.getString('question')}\nAnswer: ${responses[randomIndex]}`)
      .setColor(guildColours.special)

    interaction.reply({ embeds: [embed] });

  },
};
